apiEndpoints:
  users:
    host: '*'
    paths: ['/users/*']

http:
  port: 8080

https:
  port: 9999
  tls: {}

serviceEndpoints:
  backend:
    url: 'http://www.example.com'
pipelines:
  -
    name: ecommerce
    apiEndpoints:
      - users
    policies:
      -     # this is array of policies
        proxy:    # this is policy name
          -       # policy can multiple condition/action steps
            condition:    # optional condtion, will not execution of actions if not matched
              name: always
            action:       #
              name: proxy   # action name
              serviceEndpoint: backend  # action parameters
              param2: test  # action parameters
