APIEndpoints: # specify pipeline per domain and path
  cats:
    host: "*.cats.com"  # regexp support
    path: /             # optional defaults to /
  mycats:
    host: "*.mycats.com"
    path: /cats
  big-dogs:
    host: big-dogs.com
  animals-cats:
    host: "animals.com"
    path: /cats
  animals-dogs:
    host: "animals.com"
    path: /dogs


http:                 # if not specified EG will not start http server
  port: 9080

https:                # if not specified EG will not start https server
  port: 9443
  certificates: # will use SNI callback to provide proper certificate for domain
      "*.lunchbadger.io":
        key: "example/keys/lunchbadger.io.key.pem"
        cert: "example/keys/lunchbadger.io.cert.pem"
      "api.lunchbadger.com":
        key: "example/keys/lunchbadger.com.key.pem"
        cert: "example/keys/lunchbadger.com.cert.pem"
      "default":
        key: "example/keys/lunchbadger.io.key.pem"
        cert: "example/keys/lunchbadger.io.cert.pem"

serviceEndpoints: # urls to downstream services
  cats_service:
    url: "http://localhost"
    port: 3000
    path: /             # optional defaults to /
  dogs_service:
    url: http://localhost
    port: 4000

pipelines:
  cats_pipeline:
    APIEndpoints:
      - cats
      - mycats
      - animals-cats

    title: Cats Pipeline
    policies:
      - action:
          name: proxy # proxy to cats_service downstream service
          serviceEndpoint: cats_service

  dogs_pipeline:
    APIEndpoints:
      - big-dogs
      - animals-dogs
    title: dogs Pipeline
    policies:
      - condition:
          name: always
      #   action:
      #     name: oauth2-basic
      # - action:
      #     name: oauth2-bearer
      # - action:
      #     name: ensure-autenticated # ensure user has logged in, 403 otherwise
      # - action:
      #     name: oauth2-scope
      #     allow-scopes:
      #       - '/dogs'
        action:
          name: proxy # proxy to dogs_service downstream service
          serviceEndpoint: dogs_service

apis:
  animals:
    name: animals
    plan: free
    public_endpoints:
    - cats
    - mycats
    - dogs






