FROM node:8 as builder

ENV NODE_ENV production

WORKDIR /usr/src/app

COPY package.json package-lock.json /usr/src/app/
RUN npm install

FROM node:8-alpine

WORKDIR /usr/src/app
COPY --from=builder /usr/src/app/node_modules ./node_modules

EXPOSE 8080 9876

CMD [ "node", "lib", "index.js" ]

COPY . /usr/src/app
