# Core
db:
  redis:
    emulate: true
    namespace: EG
crypto:
  cipherKey: sensitiveKey
  algorithm: aes256
  saltRounds: 10

# OAuth2 Settings
session:
  secret: keyboard cat
  resave: false
  saveUninitialized: false
access_tokens:
  timeToExpiry: 7200000
refresh_tokens:
  timeToExpiry: 7200000
authorization_codes:
  timeToExpiry: 300000
